### ISSUE TITLE
How do you exclude multiple files and folders?

### ISSUE THREAD

**Issue by mikebronner** [reviewdog/action-misspell#29]
I've tried the following, but it does not seem to work:
```
exclude: ./public/*,./package.json,./package-lock.json,./composer.json,./composer.lock
```

Neither does the following (spaces instead of commas):
```
exclude: ./public/* ./package.json ./package-lock.json ./composer.json ./composer.lock
```

If I only exclude as follows, it works for that folder:
```
exclude: ./public/*
```

Any suggestions as to what is wrong? Thank you!

**Comment by shogo82148** [comment]
fixed by https://github.com/reviewdog/action-misspell/pull/27
