### ISSUE TITLE
Does not fail when a mistake is found

### ISSUE THREAD

**Issue by qdm12** [reviewdog/action-misspell#7]
Hi there,

This action does not seem to fail even tough some `Filtered Findings` are found. Example [here](https://github.com/qdm12/private-internet-access-docker/pull/114/checks?check_run_id=543670004). Is there a way to set it to fail the check?

Thanks!

**Comment by prologic** [comment]
I believe the `entrypoint.sh` is missing an `-error` option to the misspell script. PR up to fix this.

**Comment by qdm12** [comment]
Nice thanks! Do you want to do another release for it maybe?

**Comment by prologic** [comment]
Someone else can :) I have my day job to get back to :)
